import { notFound, redirect } from "next/navigation";
import { and, eq } from "drizzle-orm";
import type { PgColumn, PgTable } from "drizzle-orm/pg-core";
import { db } from "@/lib/db";

/** UUID matcher — a document's public URL is its number; a UUID link redirects to it. */
export const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * A document's URL is its number — `/sales/quotations/QT-2026-0001`, not the UUID.
 * The number is generated by the system, unique per org, and printed on the paper the
 * customer holds, so it is the one identifier both sides of a phone call can read out.
 *
 * Old links (and anything that still has an id in hand) keep working: a UUID in the slot
 * is looked up once and redirected to the canonical URL, so a bookmark never 404s and a
 * UUID never becomes the address bar's final state.
 *
 * Returns the number to query by. Never returns for a UUID — `redirect()` throws.
 */
export async function docNumberParam(
  raw: string,
  orgId: string,
  table: PgTable,
  cols: { id: PgColumn; number: PgColumn; organizationId: PgColumn },
  basePath: string,
  /** Appended after the number — the print routes live at `<base>/<number>/print`. */
  suffix = "",
): Promise<string> {
  const value = decodeURIComponent(raw);
  if (!UUID_RE.test(value)) return value;
  const [row] = await db
    .select({ number: cols.number })
    .from(table)
    .where(and(eq(cols.id, value), eq(cols.organizationId, orgId)))
    .limit(1);
  if (!row) notFound();
  redirect(`${basePath}/${encodeURIComponent(String(row.number))}${suffix}`);
}
