/**
 * A document's URL is its number, never its UUID.
 *
 * `/sales/quotations/9318fbde-1238-…` tells a reader nothing, cannot be read out over the
 * phone, and does not match the number printed on the paper in the customer's hand.
 * `/sales/quotations/QT-2026-0001` is the same document, addressed the way the business
 * already addresses it.
 *
 * This walks the route tree and fails on any `[id]` segment that is not on the allowlist
 * below — so the next document added to the app cannot quietly reintroduce the pattern.
 * It checks the route SHAPE only; it cannot tell whether the page then queries by number
 * (that is what `docNumberParam` is for, and what the build would catch).
 *
 *   npx tsx --tsconfig tsconfig.script.json scripts/checks/chk-doc-routes.ts
 */
import { readdirSync, statSync } from "node:fs";
import { join } from "node:path";

/**
 * Routes that are legitimately keyed by id. These are MASTER DATA, not documents: their
 * human key (`code`) is typed and edited by the user, so it is not a stable address —
 * renaming an item would silently move its page and break every existing link. A document
 * number is generated by the system and never changes, which is what makes it safe here.
 */
const ALLOWED = new Set([
  "app/(app)/accounting/assets/[id]",
  "app/(app)/accounting/banks/[id]",
  "app/(app)/inventory/items/[id]",
  "app/(print)/erp/accounting/assets/[id]",
  "app/(print)/erp/accounting/banks/[id]",
  // Generic barcode printer: /erp/barcodes/<type>/<id>, one route for every entity type.
  "app/(print)/erp/barcodes/[type]/[id]",
]);

const ROOTS = ["app/(app)", "app/(print)"];

function walk(dir: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (!statSync(p).isDirectory()) continue;
    if (name === "[id]") out.push(p.replaceAll("\\", "/"));
    walk(p, out);
  }
  return out;
}

const found = ROOTS.flatMap((r) => walk(r));
const offenders = found.filter((p) => !ALLOWED.has(p));
const stale = [...ALLOWED].filter((p) => !found.includes(p));

if (offenders.length) {
  console.error("❌ document routes keyed by UUID instead of the document number:\n");
  for (const o of offenders) console.error(`   ${o}`);
  console.error(
    "\n   Rename the segment to [number], resolve the param with docNumberParam()" +
    "\n   (lib/erp/doc-route.ts — it redirects old UUID links), and query by number." +
    "\n   If this really is master data keyed by an editable code, add it to ALLOWED here.",
  );
  process.exit(1);
}

if (stale.length) {
  console.error("❌ ALLOWED lists routes that no longer exist — remove them:\n");
  for (const s of stale) console.error(`   ${s}`);
  process.exit(1);
}

console.log(`  ✓  every document route is addressed by its number (${ALLOWED.size} master-data routes allowed)`);
